server:
  port: 80

#配置Eureka（客户端从注册中心获取服务）
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka
    register-with-eureka: false #false标识不向注册中心注册自己，当前是服务的消费者

#开启服务降级（熔断保护）
feign:
  hystrix:
    enabled: true